config/routes.rb
SaasDemo::Application.routes.draw do
  resources :meta_data

  resources :employees

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'employees#index'

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  has_many :employees
  validates_uniqueness_of :uid
  after_create :prepare_account
  before_destroy :delete_schema

  has_many :meta_data


  private

  def prepare_account
    create_schema
    load_tables
  end

  def create_schema
    PgTools.create_schema id unless PgTools.schemas.include? id.to_s
  end

  def delete_schema
    PgTools.drop_schema id
  end

  def load_tables
    return if Rails.env.test?
    PgTools.set_search_path id, false
    load "#{Rails.root}/db/schema.rb"
    SHARED_TABLES.each { |name| self.class.connection.execute %{drop table "#{name}"} }
    PgTools.restore_default_search_path
  end


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :account
  has_one :employee_detail

  accepts_nested_attributes_for :employee_detail
end

app/models/employee_detail.rb
class EmployeeDetail < ActiveRecord::Base
  belongs_to :employee
end

app/models/meta_datum.rb
class MetaDatum < ActiveRecord::Base
  belongs_to :account

  before_create :generate_field_name

  def generate_field_name
    puts self.inspect
    self.field_name = self.human_name.downcase.tr('^A-Za-z0-9', '_')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  append_before_filter :current_account

  def current_account
    unless current_user.nil?
      @current_account = current_user.account
      PgTools.set_search_path @current_account.id
    else
      PgTools.restore_default_search_path
    end
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @metadata = MetaDatum.where(:table_name=>'employee_details')
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee.build_employee_detail
    @metadata = MetaDatum.where(:table_name=>'employee_details')
  end

  # GET /employees/1/edit
  def edit
    @metadata = MetaDatum.where(:table_name=>'employee_details')
  end

  # POST /employees
  # POST /employees.json
  def create
    @fields = MetaDatum.where(:table_name=>'employee_details').pluck('field_name')
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    @fields = MetaDatum.where(:table_name=>'employee_details').pluck('field_name')
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :eid, :department, :title, employee_detail_attributes: { details: @fields })
    end
end

app/controllers/meta_data_controller.rb
class MetaDataController < ApplicationController
  before_action :set_meta_datum, only: [:show, :edit, :update, :destroy]

  # GET /meta_data
  # GET /meta_data.json
  def index
    @meta_data = MetaDatum.all
  end

  # GET /meta_data/1
  # GET /meta_data/1.json
  def show
  end

  # GET /meta_data/new
  def new
    @meta_datum = MetaDatum.new
  end

  # GET /meta_data/1/edit
  def edit
  end

  # POST /meta_data
  # POST /meta_data.json
  def create
    @meta_datum = MetaDatum.new(meta_datum_params)

    respond_to do |format|
      if @meta_datum.save
        format.html { redirect_to @meta_datum, notice: 'Meta datum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meta_datum }
      else
        format.html { render action: 'new' }
        format.json { render json: @meta_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meta_data/1
  # PATCH/PUT /meta_data/1.json
  def update
    respond_to do |format|
      if @meta_datum.update(meta_datum_params)
        format.html { redirect_to @meta_datum, notice: 'Meta datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meta_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meta_data/1
  # DELETE /meta_data/1.json
  def destroy
    @meta_datum.destroy
    respond_to do |format|
      format.html { redirect_to meta_data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meta_datum
      @meta_datum = MetaDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meta_datum_params
      params.require(:meta_datum).permit(:table_name, :field_name, :account_id, :human_name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # POST /resource
  def create
    build_resource(sign_up_params)
    account = build_account(params)

    if account.valid?
      if resource.save
        account.save
        resource.account_id = account.id
        resource.save
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_navigational_format?
          sign_up(resource_name, resource)
          respond_with resource, :location => after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
          expire_session_data_after_sign_in!
          respond_with resource, :location => after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        respond_with resource
      end
    else
      set_flash_message :error, "Account Name is invalid or already taken!"
      clean_up_passwords resource
      redirect_to new_user_registration_url
    end
  end

  protected


  def build_account(params)
    Account.new name: params[:account_name], uid: params[:account_name].tr('^A-Za-z0-9', '_')
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/meta_data_helper.rb
module MetaDataHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :eid %><br>
    <%= f.text_field :eid %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <%= f.fields_for :employee_detail do |fields| %>
    <%= fields.fields_for :details, @employee.employee_detail.details do |d| %>
      <% @metadata.each do |field| %>
        <div class="field">
          <%= d.label field.human_name %><br>
          <%= d.text_field field.field_name, :value=> (@employee.employee_detail.details[field.field_name] unless @employee.employee_detail.details.nil? )%>
        </div>  
      <% end %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1> ERP for <%= @current_account.name %></h1>

<h2>Listing employees</h2>

<table border=1>
  <thead>
    <tr>
      <th>Name</th>
      <th>Eid</th>
      <th>Department</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.eid %></td>
        <td><%= employee.department %></td>
        <td><%= employee.title %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>
<%= link_to 'Edit Employee Fields', meta_data_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Eid:</strong>
  <%= @employee.eid %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.title %>
</p>

<h4>More Details</h4>
<% unless @employee.employee_detail.nil? %>
  <% puts "test" %>
  <% puts @employee.employee_detail.details.inspect %>
  <% @metadata.each do |field| %>
    <p>
      <strong><%= field.human_name %></strong>
      <%= @employee.employee_detail.details[field.field_name] %>
    </p>
  <% end %>
<% end %>        

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<style type="text/css">
  ul.hmenu {
    list-style: none; 
    margin: 0 0 2em;
    padding: 0;
  }

  ul.hmenu li {
    display: inline;  
  }
</style>
<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>
<%= flash[:error] %>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/meta_data/_form.html.erb
<%= form_for(@meta_datum) do |f| %>
  <% if @meta_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meta_datum.errors.count, "error") %> prohibited this meta_datum from being saved:</h2>

      <ul>
      <% @meta_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :table_name %><br>
    <%= f.select :table_name, options_for_select(DYNAMIC_TABLES) %>
  </div>
  <div class="field">
    <%= f.label :field_name %><br>
    <%= f.text_field :human_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meta_data/edit.html.erb
<h1>Editing meta_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @meta_datum %> |
<%= link_to 'Back', meta_data_path %>

app/views/meta_data/index.html.erb
<h1>Listing meta_data</h1>

<table border=1>
  <thead>
    <tr>
      <th>Table name</th>
      <th>Field name</th>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meta_data.each do |meta_datum| %>
      <tr>
        <td><%= meta_datum.table_name %></td>
        <td><%= meta_datum.field_name %></td>
        <td><%= meta_datum.account_id %></td>
        <td><%= link_to 'Show', meta_datum %></td>
        <td><%= link_to 'Edit', edit_meta_datum_path(meta_datum) %></td>
        <td><%= link_to 'Destroy', meta_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meta datum', new_meta_datum_path %>
<%= link_to 'Employees', employees_path %>

app/views/meta_data/new.html.erb
<h1>New meta_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', meta_data_path %>

app/views/meta_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table name:</strong>
  <%= @meta_datum.table_name %>
</p>

<p>
  <strong>Field name:</strong>
  <%= @meta_datum.field_name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @meta_datum.account_id %>
</p>

<%= link_to 'Edit', edit_meta_datum_path(@meta_datum) %> |
<%= link_to 'Back', meta_data_path %>